############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
############################################################
set_directive_pipeline "one_test/one_test_label1"
set_directive_pipeline "one_test/fermat_test_label0"
set_directive_pipeline "one_test/fermat_test_label1"
set_directive_pipeline "one_test/mul1_label"
set_directive_pipeline "one_test/sum1_label"
set_directive_pipeline "one_test/sub1_label"
set_directive_pipeline "one_test/shift1_label"
set_directive_pipeline "one_test/sub2_label"
set_directive_pipeline "one_test/one_test_label7"
set_directive_pipeline "one_test/one_test_label8"
set_directive_pipeline "one_test/one_test_label9"
set_directive_pipeline "fermat_test/fermat_test_label3"
set_directive_pipeline "fermat_test/fermat_test_label4"
set_directive_loop_flatten -off "one_test/one_test_label6"
set_directive_dependence -variable cy -type inter -dependent true "one_test/mul1_label"
set_directive_dependence -variable cy -type inter -dependent true "one_test/fermat_test_label0"
set_directive_dependence -variable cy -type inter -dependent true "one_test/one_test_label1"
set_directive_dependence -variable cy -type inter -dependent true "one_test/fermat_test_label1"
set_directive_dependence -variable cy -type inter -dependent true "one_test/sum1_label"
set_directive_dependence -variable borrow -type inter -dependent true "one_test/sub1_label"
set_directive_dependence -variable last_shifted -type inter -dependent true "one_test/sub1_label"
set_directive_dependence -variable carry -type inter -dependent true "one_test/shift1_label"
set_directive_dependence -variable borrow -type inter -dependent true "one_test/sub2_label"
set_directive_dependence -variable last_shifted -type inter -dependent true "one_test/sub2_label"
set_directive_dependence -variable cy -type inter -dependent true "one_test/one_test_label7"
set_directive_dependence -variable cy -type inter -dependent true "one_test/one_test_label8"
set_directive_dependence -variable borrow -type inter -dependent true "one_test/one_test_label9"
set_directive_dependence -variable last_shifted -type inter -dependent true "one_test/one_test_label9"
set_directive_dependence -variable cy -type intra -dependent true "one_test/mul1_label"
set_directive_dependence -variable cy -type intra -dependent true "one_test/fermat_test_label0"
set_directive_dependence -variable cy -type intra -dependent true "one_test/one_test_label1"
set_directive_dependence -variable cy -type intra -dependent true "one_test/fermat_test_label1"
set_directive_dependence -variable cy -type intra -dependent true "one_test/sum1_label"
set_directive_dependence -variable borrow -type intra -dependent true "one_test/sub1_label"
set_directive_dependence -variable last_shifted -type intra -dependent true "one_test/sub1_label"
set_directive_dependence -variable carry -type intra -dependent true "one_test/shift1_label"
set_directive_dependence -variable borrow -type intra -dependent true "one_test/sub2_label"
set_directive_dependence -variable last_shifted -type intra -dependent true "one_test/sub2_label"
set_directive_dependence -variable cy -type intra -dependent true "one_test/one_test_label7"
set_directive_dependence -variable cy -type intra -dependent true "one_test/one_test_label8"
set_directive_dependence -variable borrow -type intra -dependent true "one_test/one_test_label9"
set_directive_dependence -variable last_shifted -type intra -dependent true "one_test/one_test_label9"
set_directive_loop_flatten -off "one_test/one_test_label5"
